language: objective-c
osx_image: xcode8.3

cache:
directories:
- Carthage

# Install lfs
before_install:
- brew update
- brew install git-lfs
- brew outdated carthage || brew upgrade carthage
- git lfs install
before_script:
- git lfs pull
- carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds

# set script mannualy due to xcode8.3 non supporting xctool
script:
- xcodebuild test -project C8oSDKiOS.xcodeproj -scheme C8oSDKiOS -destination 'platform=iOS Simulator,name=iPhone 7 Plus,OS=10.3.1'

