language: objective-c
osx_image: xcode9.2
before_install:
- brew update && brew install git-lfs
- git lfs install
- chmod +x ./scripts/ci-script.bash
before_script:
- git lfs pull
script:
- rm -rf ./C8oSDK.zip
- mkdir -p ./buildSim
- mkdir -p ./universal_outputfolder
- "./scripts/ci-script.bash"
- xcodebuild test -workspace C8oSDKiOS.xcworkspace -scheme C8oSDKiOS -destination
  'platform=iOS Simulator,name=iPhone X,OS=11.2'
- xcodebuild -workspace C8oSDKiOS.xcworkspace -scheme C8oSDKiOS archive
- mkdir Frameworks && cp -r ./universal_outputfolder/C8o.framework ./Frameworks/ &&
  zip -r -X C8oSDK.zip ./Frameworks/C8o.framework LICENSE
deploy:
  provider: releases
  api_key:
    secure: NtvoZYdFl1iOB1zwNEh28pvvUDWkmzEDt/UymbritZ5DxHx3or/09A+7X3Io1Ujl3Lp9SHMasG1PUElPkjE3pMw7bRH0N3xlje49FNE7WYAtXSmqABTUIQT9At28h8TtN3gvC8+Khn6M9+mI1i/x3kQwdTI0F7YAZqD2aW/0sWbNcv3D2GSmUa6OAVyqupmnGVZKCGWlicIcJ1J0yba8P97DgXD3LiytHfCmouKdRRszy67wKrrELnbaIHhKYP6Kxg88sIT8hMlTKSLqsCcXEH72UcX8AooFsiUXnPXurDWoQlQ3dbL+EWMl2XD4cr+Y2nIEsx2M7MWh4jeR94IKNkrhRmhoTwYLxiSTVsySiM2AbR5pSulngIPzVJa9rOneGtNs0eAea2WwoorzOqTqRkXMEGJ96uOHx0+i1PTuoqHNAyXDHfbth8W/6wvcSh+ZoCYiyzhZbSbMiiqg+g+IL8N6kzRSNh94vgutoOdV2l5q2QckB6QrsC+k70m5OpEbhEcThPP2djv5luStp0BTxIouzGt0WzQcBvjIUtxCVMNZc3Kmm2F0XVSYP8loTq5A/wIDOUt+IzBopkDLFHijed5VqBaEiTw0QSpPNfwFa/tWaSCuU7zfGBFYrv6AKm7TecRhwskqnOPZd5pw9BTPqLqgyZvjucrEsaUP/98HOyY=
  file: "C8oSDK.zip"
  skip_cleanup: true
  on:
    tags: true
