language: objective-c
osx_image: xcode8.3

# Install lfs
before_install:
- brew update && brew install git-lfs
- git lfs install
before_script:
- git lfs pull

# set script mannualy due to xcode8.3 non supporting xctool
script:
- xcodebuild test -workspace C8oSDKiOS.xcworkspace -scheme C8oSDKiOS -destination 'platform=iOS Simulator,name=iPhone 7 Plus,OS=10.3.1'

